## Лабораторная работа №1 | Вариант 5

Выполнил: Бойцов Иван Алексеевич

### 1. Numpy

In [1]:
import numpy as np

1. Создайте единичную матрицу размером 3х3

In [32]:
matrix = np.identity(3)

print("Единичный вектор :\n", matrix)

Единичный вектор :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Создайте кастомный dtype который описывает цвет состоящий из 4х unsigned bytes(RGBA пиксель)

In [33]:
rgba = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('a' , np.uint8)
])

# Example
pixel = np.array([(255, 128, 64, 255)], dtype = rgba)
print(pixel)

[(255, 128, 64, 255)]


3. Как игнорировать все numpy warnings(не рекомендуем к использованию)?

In [74]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

4. Создайте случайный вектор размера 10 и отсортируйте его

In [34]:
vec = np.random.random(10)

print("Оригинальный вектор:", vec)

vec_sorted = np.sort(vec)

print("Отсортированный вектор: ", vec_sorted)

Оригинальный вектор: [0.0465929  0.79838839 0.38914204 0.01587089 0.38166123 0.76611544
 0.62215028 0.55419872 0.83110322 0.74643721]
Отсортированный вектор:  [0.01587089 0.0465929  0.38166123 0.38914204 0.55419872 0.62215028
 0.74643721 0.76611544 0.79838839 0.83110322]


5. Создайте read-only массив(неизменяемый)

In [35]:
arr = np.zeros(10)

arr.flags.writeable = False

print("Read-only массив: ",arr)

Read-only массив:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


6. Рассмотрим случайную матрицу размером 10х2, представляющую декартовы координаты, преобразуем их в полярные координаты

In [36]:
# Декартовы координаты
cartesian_coords = np.random.rand(10, 2) * 10

print("Декартовы координаты: \n", cartesian_coords)

x = cartesian_coords[:, 0] # Координаты X
y = cartesian_coords[:, 1] # Координаты Y

# Вычисляем полярыне координаты по формуле
r = np.sqrt(x**2 + y**2) # Radius
theta = np.arctan(y, x) # Corner in radians

polar_coords = np.column_stack((r, theta))

print("Полярные координаты: \n", polar_coords)

Декартовы координаты: 
 [[6.52415288 1.96048137]
 [8.30401719 2.9578063 ]
 [9.45615592 7.91808996]
 [5.961861   9.92025474]
 [0.32496955 6.5748145 ]
 [0.06824553 7.83143395]
 [1.13570601 2.51785187]
 [0.23539013 7.06186498]
 [3.35056405 9.97905841]
 [7.20363749 4.99134301]]
Полярные координаты: 
 [[ 6.812346    1.09911822]
 [ 8.81506209  1.24477233]
 [12.33349234  1.44516835]
 [11.57390344  1.47033183]
 [ 6.58284064  1.41985758]
 [ 7.8317313   1.44379307]
 [ 2.76213798  1.19273721]
 [ 7.06578697  1.43012595]
 [10.52653249  1.4709199 ]
 [ 8.76389743  1.37306725]]


7. Создайте структурированный массив с координатами x и y, охватывающий область [0,1]x[0,1]

In [41]:
coords = [('x', np.float64), ('y', np.float64)]

num_points = 5
coord = np.zeros(num_points, dtype=coords)

coord['x'] = np.random.rand(num_points)
coord['y'] = np.random.rand(num_points)

print("Структурированный массив координат (x, y):\n", coord)

Структурированный массив координат (x, y):
 [(0.26092246, 0.86265564) (0.26505513, 0.91901891)
 (0.69483903, 0.52399932) (0.01211719, 0.74849658)
 (0.83582611, 0.34251786)]


8. Учитывая два массива X и Y, постройте матрицу Коши $C$ ($C_{ij} =\frac{1}{x_i - y_j}$)

In [48]:
x = np.random.normal(size=(5))
y = np.random.normal(size=(5))

# Преобразование в вектор массив и вычет из каждого элемента массива y
C = 1.0 / (x[:, np.newaxis] - y)

print("Матрица Коши: \n", C)

Матрица Коши: 
 [[ -1.55218215   3.54643005  -2.59866986  -8.12917748 -65.0923447 ]
 [ -0.55238484  -1.13108851  -0.64479103  -0.77574013  -0.84642427]
 [ -0.62280837  -1.47188193  -0.74283815  -0.9221777   -1.02381516]
 [ -0.66559374  -1.73553867  -0.80452081  -1.01918373  -1.144785  ]
 [ -0.67291207  -1.78619185  -0.81523762  -1.0364438   -1.16660691]]


9. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [49]:
arr = np.array([1.5, 1.4, 2.9, 3.1, 4.5, 0.5], dtype=np.float32)

arr = arr.astype(np.int32, copy=False)

print("Конвертированный массив: ", arr)

Конвертированный массив:  [1 1 2 3 4 0]


10. Как случайно заменить p элементов в 2D массиве?

In [63]:
arr = np.random.randint(low=1, high=100, size=[5,5])

p = 5 # Количество заменяемых элементов
print("Оригинальный массив: \n" , arr)

np.put(arr, np.random.choice(range(arr.size), p, replace=False), 0)

print("Массив со случайными заменами: \n", arr)

Оригинальный массив: 
 [[80 71 90 98 40]
 [79 81 70 79 86]
 [57 17 36 58 25]
 [57 69 79  4 92]
 [ 4 25 37 29 51]]
Массив со случайными заменами: 
 [[80 71 90  0 40]
 [ 0  0 70 79 86]
 [57 17 36 58 25]
 [57  0 79  4 92]
 [ 4 25 37 29  0]]


### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом 

Классический начальный набор данных - данные пассажиров титаника.

Файл: `data.csv`

```
PassangerId - уникальный номер пассажира
Survived - выжил человек или нет
Pclass - класс обслуживания
Name - имя человека, обращение к ней/нему
Sex - пол человека
Age - возраст на момент крушения
SibSp - количество братьев и сестер / супругов на борту "Титаника"
Parch - количество родителей / детей на борту "Титаника"
Ticket - номер билета
Fare - стоимость проезда для пассажиров
Cabin - каюта
Embarked - причал отбытия. C = Cherbourg Q = Queenstown S = Southampton
```

In [64]:
import pandas as pd

In [81]:
DATA_SET = "D:\Work\VS Code Projects\ML-Practise\Labs\Lab01\data.csv"

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
C:\Users\ivanb\AppData\Local\Temp\ipykernel_37100\2044636768.py:1: SyntaxWarning: invalid escape sequence '\W'
  DATA_SET = "D:\Work\VS Code Projects\ML-Practise\Labs\Lab01\data.csv"


1. Узнайте сколько было на борту человек

In [186]:
df = pd.read_csv(DATA_SET)

print("На борту было", df.shape[0], "человек(а)")

На борту было 891 человек(а)


2. Какой медианный и средний возраста пассажиров

In [185]:
mean_age = df['Age'].mean()
median_age = df['Age'].median()

print("Медианный возраст:", median_age, '\n'
      "Средниый возраст:", mean_age)

Медианный возраст: 28.0 
Средниый возраст: 29.69911764705882


3. Посчитайте процент выживаемости детей(до 16 лет) и взрослых

In [176]:
kids_survive = df[df['Age'] < 16]['Survived'].mean() * 100

adult_survive = df[df['Age'] >= 16]['Survived'].mean() * 100

survive = df['Survived'].mean() * 100

print("Выживаемость детей:", kids_survive, '\n'
      "Выживаемость взрослых:", adult_survive, '\n'
      "Общая выживаемость", survive)

Выживаемость детей: 59.036144578313255 
Выживаемость взрослых: 38.193343898573694 
Общая выживаемость 38.38383838383838


4. Верна ли гипотеза, что женщины и дети сажались в шлюпки первыми и выживали больше?

In [156]:
woman_survive = df[(df['Age'] >= 16) & (df['Sex'] == 'female')]['Survived'].shape[0]

kids_survive = df[df['Age'] < 16]['Survived'].shape[0]

man_survive = df[(df['Age'] >= 16) & (df['Sex'] == 'male')]['Survived'].shape[0]

print("Женщин выжило:", woman_survive, '\n'
      "Детей выжило:", kids_survive, '\n'
      "Мужчин выжило:", man_survive, '\n')

woman_survive_per = df[(df['Age'] >= 16) & (df['Sex'] == 'female')]['Survived'].mean() * 100

kids_survive_per = df[df['Age'] < 16]['Survived'].mean() * 100

man_survive_per = df[(df['Age'] >= 16) & (df['Sex'] == 'male')]['Survived'].mean() * 100

print("Женщин в процентном соотношении выжило:", woman_survive_per, '\n'
      "Детей в процентном соотношении выжило:", kids_survive_per, '\n'
      "Мужчин в процентном соотношении выжило:", man_survive_per, '\n')

print("С точки зрения процентов, то теория верна - женщин и детей выжило больше")

Женщин выжило: 218 
Детей выжило: 83 
Мужчин выжило: 413 

Женщин в процентном соотношении выжило: 77.52293577981652 
Детей в процентном соотношении выжило: 59.036144578313255 
Мужчин в процентном соотношении выжило: 17.433414043583532 

С точки зрения процентов, то теория верна - женщин и детей выжило больше


5. Зависит ли выживаемость от класса обслуживания?

In [147]:
first_class = df[df['Pclass'] == 1]['Survived'].mean() * 100
second_class = df[df['Pclass'] == 2]['Survived'].mean() * 100
third_class = df[df['Pclass'] == 3]['Survived'].mean() * 100

print("Выживаемость первого класса", first_class, '\n'
      "Выживаемость второго класса", second_class, '\n'
      "Выживаемость третьего класса", third_class, '\n')

print("Да, выживаемость зависит от класса, люди из третьего класса выжили в меньшем соотношении")

Выживаемость первого класса 62.96296296296296 
Выживаемость второго класса 47.28260869565217 
Выживаемость третьего класса 24.236252545824847 

Да, выживаемость зависит от класса, люди из третьего класса выжили в меньшем соотношении


6. Посчитайте средний возраст умерших женщин и мужчин

In [163]:
woman_dead = df[(df['Survived'] == 0) & (df['Sex'] == 'female')]['Age'].mean()
man_dead = df[(df['Survived'] == 0) & (df['Sex'] == 'male')]['Age'].mean()

dead_age = df[df['Survived'] == 0]['Age'].mean()

print("Средний возраст умерших:", dead_age, '\n'
      "Средний возраст умерших женщин:", woman_dead, '\n'
      "Средний возраст умерших мужчин:", man_dead)

Средний возраст умерших: 30.62617924528302 
Средний возраст умерших женщин: 25.046875 
Средний возраст умерших мужчин: 31.618055555555557


7. Различается ли процент выживаемости пассажиров с хотя бы одним родственником на борту и одиночек?

In [178]:
zero_siblings = df[(df['SibSp'] == 0) & (df['Parch'] == 0)]['Survived'].mean() * 100
have_siblings = df[(df['SibSp'] >= 1) | (df['Parch'] >= 1)]['Survived'].mean() * 100

print("Выживаемость одиночек:", zero_siblings, '\n'
      "Выживаемость людей, имеющих родственников:", have_siblings, '\n'
      "Процент выживаемости людей, имеющих родственников, на 20% больше")

Выживаемость одиночек: 30.353817504655495 
Выживаемость людей, имеющих родственников: 50.56497175141242 
Процент выживаемости людей, имеющих родственников, на 20% больше


8. Различается ли средняя стоимость билета у умерших и выживших пассажиров?

In [180]:
fare_dead = df[df['Survived'] == 0]['Fare'].mean()
fare_survive = df[df['Survived'] == 1]['Fare'].mean()

print("Средняя стоимость билета умершего пассажира:", fare_dead, '\n'
      "Средняя стоимость билета выжившего пассажира:", fare_survive, '\n'
      "У выживших пассажиров средняя стоимость билета больше")

Средняя стоимость билета умершего пассажира: 22.117886885245902 
Средняя стоимость билета выжившего пассажира: 48.39540760233918 
У выживших пассажиров средняя стоимость билета больше


9. Выведите максимальный и минимальный возраст выживших пассажиров во 2 классе обслуживания

In [189]:
second_class_max_age = df[(df['Pclass'] == 2) & (df['Survived'] == 1)]['Age'].max()
second_class_min_age = df[(df['Pclass'] == 2) & (df['Survived'] == 1)]['Age'].min()

print("Максимальный возраст выжившего пассажира из второго класса", second_class_max_age, '\n'
      "Минимальный возраст выжившего пассажира из второго класса", second_class_min_age)

Максимальный возраст выжившего пассажира из второго класса 62.0 
Минимальный возраст выжившего пассажира из второго класса 0.67


10. Подтвердите или опровергните гипотезу: молодым мужчинам(от 18 лет) выжить легче, чем более взрослым

In [213]:
yong_man = df[(df['Sex'] == 'male') & (df['Age'] >= 18) & (df['Age'] < 30)]['Survived'].mean() * 100
adult_man = df[(df['Sex'] == 'male') & (df['Age'] >= 30)]['Survived'].mean() * 100

print("Зависит от предела, на котором заканчивается категория молодой мужчина. Если предположить, что молодой - это до 30 лет, то получаются следующие проценты", "\n"
      "Выживаемость молодых мужчин:", yong_man, '\n'
      "Выживаемость более взрослых мужчин", adult_man, '\n'
      "Как видно из процентных соотношений, взрослые мужчины выживают с большей вероятностью", "\n")

yong_man = df[(df['Sex'] == 'male') & (df['Age'] >= 18) & (df['Age'] < 40)]['Survived'].mean() * 100
adult_man = df[(df['Sex'] == 'male') & (df['Age'] >= 40)]['Survived'].mean() * 100

print("Если предположить, что взрослые мужчины - возраст до 40 лет, то получаются уже другие проценты", "\n"
      "Выживаемость молодых мужчин:", yong_man, '\n'
      "Выживаемость более взрослых мужчин", adult_man, '\n'
      "В этот раз они практически равны, однако виживаемость молодых мужчин будет на 0.4% больше", "\n")

yong_man = df[(df['Sex'] == 'male') & (df['Age'] >= 18) & (df['Age'] < 50)]['Survived'].mean() * 100
adult_man = df[(df['Sex'] == 'male') & (df['Age'] >= 50)]['Survived'].mean() * 100

print("Если предположить, что взрослые мужчины - возраст до 50 лет, то получаются уже другие проценты", "\n"
      "Выживаемость молодых мужчин:", yong_man, '\n'
      "Выживаемость более взрослых мужчин", adult_man, '\n'
      "Наконец, если сказть, что возраст молодого человека - до 50 лет, то только в таком случае молодой мужчина будет сильно обгонять процентную выживаемость более взрослого", "\n")

print("Однако, я считаю возраст молодого человека до 30 более корректным, поэтому возьму за основу эту статистику и опровергну теорию, сказав что по процентному соотношению взрослому человеку выжить легче")

yong_man = df[(df['Sex'] == 'male') & (df['Age'] >= 18) & (df['Age'] < 30)]['Survived'].mean() * 100
adult_man = df[(df['Sex'] == 'male') & (df['Age'] >= 30)]['Survived'].mean() * 100

print("Выживаемость молодых мужчин:", yong_man, '\n'
      "Выживаемость более взрослых мужчин", adult_man,)

Зависит от предела, на котором заканчивается категория молодой мужчина. Если предположить, что молодой - это до 30 лет, то получаются следующие проценты 
Выживаемость молодых мужчин: 15.64245810055866 
Выживаемость более взрослых мужчин 19.444444444444446 
Как видно из процентных соотношений, взрослые мужчины выживают с большей вероятностью 

Если предположить, что взрослые мужчины - возраст до 40 лет, то получаются уже другие проценты 
Выживаемость молодых мужчин: 17.832167832167833 
Выживаемость более взрослых мужчин 17.431192660550458 
В этот раз они практически равны, однако виживаемость молодых мужчин будет на 0.4% больше 

Если предположить, что взрослые мужчины - возраст до 50 лет, то получаются уже другие проценты 
Выживаемость молодых мужчин: 18.367346938775512 
Выживаемость более взрослых мужчин 13.461538461538462 
Наконец, если сказть, что возраст молодого человека - до 50 лет, то только в таком случае молодой мужчина будет сильно обгонять процентную выживаемость более взрос

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Постройте гистограмму распределения возростов пассажиров

2. Постройте гистограммы распределения цен для пассажиров разных классов

3. Постройте зависимость цены от возраста пассажира

4. Постройте box plot отображающий распределение цен на билеты в разных классах

5. Визуализируйте распределение долей выживших среди мужчин, женщин и детей(до 16 лет)

6. Сравните плотности распределения возростов выживших и умерших пассажиров, сделайте выводы

7. Постройте круговую диаграмму отображающую выживаемость мужчин и женщин в разных классах обслуживания(визуализация должна быть интуитивно понятная без объяснений, женщины и мужчины соответствующих классов объеденены визуально в одну группу и 2 подгруппы)*

\* Задание на доп. балл